#!/usr/bin/env python3
"""Atomic LAN interface switch with watchdog rollback.

Usage: switch_interface.py <new_iface>

Moves the gateway's static IP config (netplan) to <new_iface>, re-applies
TProxy iptables rules, restarts dnsmasq and announces the new MAC via
gratuitous ARP. If the router becomes unreachable within WATCHDOG_SEC,
the previous configuration is restored automatically.

Run detached from shunt-web (systemd-run) so a web-service restart cannot
kill the watchdog mid-switch. Progress is written to STATUS_FILE and
polled by the UI via GET /api/network/switch-status.
"""
import json, re, shutil, socket, struct, subprocess, sys, time
from pathlib import Path

BASE         = Path("/opt/shunt")
NET_CONF     = BASE / "config" / "network.conf"
DEBUG_LOG    = BASE / "logs" / "netswitch-debug.log"
SINGBOX_CONF = Path("/etc/sing-box/config.json")
STATUS_FILE  = BASE / "config" / "netswitch-status.json"
ROLLBACK_DIR = BASE / "config" / "netswitch-rollback"
NETPLAN_DIR  = Path("/etc/netplan")
IPTABLES_SH  = BASE / "scripts" / "iptables.sh"
WATCHDOG_SEC  = 45
WAIT_LINK_SEC = 90   # time for the user to move the cable to the new port
PING_OK_NEED  = 2

_status: dict = {}

def set_status(stage: str, **kw) -> None:
    _status.update({"stage": stage, "ts": time.time()}, **kw)
    tmp = STATUS_FILE.with_suffix(".tmp")
    tmp.write_text(json.dumps(_status))
    tmp.rename(STATUS_FILE)

def run(*cmd: str, check: bool = True, timeout: int = 30) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True, check=check, timeout=timeout)

def read_net_conf() -> dict:
    out = {}
    for line in NET_CONF.read_text().splitlines():
        if "=" in line and not line.lstrip().startswith("#"):
            k, v = line.split("=", 1)
            out[k.strip()] = v.strip()
    return out

def write_net_conf(lan_if: str, router_ip: str) -> None:
    NET_CONF.write_text(
        f"# Updated by switch_interface.py {time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}\n"
        f"LAN_IF={lan_if}\nROUTER_IP={router_ip}\n")

def iface_mac(iface: str) -> str:
    return Path(f"/sys/class/net/{iface}/address").read_text().strip()

def iface_carrier(iface: str) -> bool:
    try:
        return Path(f"/sys/class/net/{iface}/carrier").read_text().strip() == "1"
    except OSError:
        return False

def current_ip_prefix(iface: str) -> str | None:
    r = run("ip", "-4", "addr", "show", iface, check=False)
    m = re.search(r"inet (\d+\.\d+\.\d+\.\d+/\d+)", r.stdout)
    return m.group(1) if m else None

def parse_nameservers() -> list[str]:
    """Best-effort: reuse nameservers from the existing netplan config."""
    ns = []
    for f in sorted(NETPLAN_DIR.glob("*.yaml")):
        try:
            in_addr = False
            for line in f.read_text().splitlines():
                if "nameservers" in line: in_addr = True; continue
                if in_addr:
                    m = re.search(r"addresses:\s*\[([^\]]+)\]", line)
                    if m:
                        ns += [x.strip() for x in m.group(1).split(",")]
                        in_addr = False
                    elif re.match(r"\s*-\s*[\d.]+", line):
                        ns.append(line.split("-", 1)[1].strip())
                    elif line.strip() and not line.startswith(" " * 8):
                        in_addr = False
        except OSError:
            pass
    return ns or ["9.9.9.9"]

def build_yaml(iface: str, mac: str, ip_prefix: str, router_ip: str, ns: list[str]) -> str:
    ns_list = ", ".join(ns)
    return f"""# Generated by shunt switch_interface.py — do not edit by hand.
# Active LAN interface: {iface} ({mac})
network:
  version: 2
  ethernets:
    {iface}:
      match:
        macaddress: {mac}
      set-name: {iface}
      dhcp4: false
      addresses:
        - {ip_prefix}
      routes:
        - to: default
          via: {router_ip}
          metric: 50
      nameservers:
        addresses: [{ns_list}]
"""

def apply_netplan() -> None:
    run("netplan", "apply", timeout=60)
    time.sleep(2)  # let addresses settle before iptables reads them

def reapply_services() -> None:
    run("bash", str(IPTABLES_SH), "up", timeout=60)
    run("systemctl", "restart", "dnsmasq", check=False, timeout=30)

def rebind_singbox(iface: str) -> None:
    """sing-box pins route.default_interface and the bypass outbound's
    bind_interface to a concrete NIC — retarget them or the gateway's own
    egress dies after the switch."""
    if not SINGBOX_CONF.exists():
        return
    try:
        conf = json.loads(SINGBOX_CONF.read_text())
        changed = False
        if conf.get("route", {}).get("default_interface") not in (None, iface):
            conf["route"]["default_interface"] = iface
            changed = True
        for o in conf.get("outbounds", []):
            if o.get("bind_interface") not in (None, iface):
                o["bind_interface"] = iface
                changed = True
        if changed:
            SINGBOX_CONF.write_text(json.dumps(conf, ensure_ascii=False, indent=2))
            run("systemctl", "restart", "sing-box", check=False, timeout=30)
    except Exception as e:
        print(f"sing-box rebind failed (non-fatal): {e}", file=sys.stderr)

def capture_debug(iface: str, router_ip: str) -> None:
    """Wire-level evidence for a failing DNS probe: capture while probing."""
    try:
        with DEBUG_LOG.open("a") as f:
            f.write(f"\n===== netswitch debug {time.strftime('%F %T')} iface={iface} =====\n")
            cap = subprocess.Popen(
                ["tcpdump", "-i", iface, "-c", "30", "-n", "-v", "--immediate-mode",
                 f"(udp port 53 or icmp or arp) and host {router_ip}"],
                stdout=f, stderr=subprocess.STDOUT, text=True)
            for _ in range(4):
                ping(router_ip); dns_probe(router_ip); time.sleep(0.5)
            try: cap.wait(timeout=8)
            except subprocess.TimeoutExpired: cap.kill()
            for cmd in (["ethtool", "-k", iface], ["ip", "rule", "show"],
                        ["ip", "route", "show", "table", "main"],
                        ["ip", "neigh", "show"]):
                r = run(*cmd, check=False)
                f.write(f"\n--- {' '.join(cmd)} ---\n{r.stdout}{r.stderr}")
    except Exception as e:
        print(f"debug capture failed (non-fatal): {e}", file=sys.stderr)

def disable_usb_nic_offload(iface: str) -> None:
    """r8152/USB NICs are known to corrupt UDP checksums with TX offload on
    some firmware — ICMP works, DNS dies. Costs little CPU to disable."""
    dev = Path(f"/sys/class/net/{iface}/device").resolve()
    if "usb" not in str(dev):
        return
    run("ethtool", "-K", iface, "tx", "off", "rx", "off", check=False)

def gratuitous_arp(iface: str, ip: str, repeats: int = 6) -> None:
    """Announce IP→MAC binding so the router and clients update ARP caches.

    Sends both forms because devices differ in which one they honor:
    - GARP request (op=1, target MAC zeroed) — what keepalived/Windows send
    - GARP reply  (op=2, target MAC = own)   — what arping -U sends
    Repeated over several seconds: a single burst right after link-up is
    easy to lose while the switch port is still learning.
    """
    try:
        mac = bytes.fromhex(iface_mac(iface).replace(":", ""))
        ip_b = socket.inet_aton(ip)
        hdr = b"\xff" * 6 + mac + b"\x08\x06"
        arp_req = hdr + struct.pack("!HHBBH", 1, 0x0800, 6, 4, 1) + \
                  mac + ip_b + b"\x00" * 6 + ip_b
        arp_rep = hdr + struct.pack("!HHBBH", 1, 0x0800, 6, 4, 2) + \
                  mac + ip_b + mac + ip_b
        s = socket.socket(socket.AF_PACKET, socket.SOCK_RAW)
        s.bind((iface, 0))
        for _ in range(repeats):
            s.send(arp_req)
            s.send(arp_rep)
            time.sleep(1.0)
        s.close()
    except OSError as e:
        print(f"GARP failed (non-fatal): {e}", file=sys.stderr)

def ping(host: str) -> bool:
    return subprocess.run(["ping", "-c", "1", "-W", "2", host],
                          capture_output=True).returncode == 0

def dns_probe(router_ip: str) -> bool:
    """Plain UDP DNS query to the router — catches the case where ICMP works
    but UDP is broken (stale ARP on one side, NIC checksum-offload bugs)."""
    query = (b"\x12\x34\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00"
             b"\x06google\x03com\x00\x00\x01\x00\x01")
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.settimeout(2)
        s.sendto(query, (router_ip, 53))
        data, _ = s.recvfrom(512)
        s.close()
        return len(data) > 12
    except OSError:
        return False

def watchdog(router_ip: str) -> tuple[bool, str]:
    """Healthy = router answers both ping AND a UDP DNS query."""
    deadline = time.time() + WATCHDOG_SEC
    ok = 0
    last = "нет ответа"
    while time.time() < deadline:
        p, d = ping(router_ip), dns_probe(router_ip)
        if p and d:
            ok += 1
            if ok >= PING_OK_NEED:
                return True, "ok"
        else:
            ok = 0
            last = ("ping ок, но UDP/DNS к роутеру не проходит "
                    "(старый ARP-кэш или офлоад USB-адаптера)" if p and not d
                    else "роутер не отвечает на ping")
        time.sleep(1)
    return False, last

def backup_configs() -> None:
    if ROLLBACK_DIR.exists():
        shutil.rmtree(ROLLBACK_DIR)
    (ROLLBACK_DIR / "netplan").mkdir(parents=True)
    for f in NETPLAN_DIR.glob("*.yaml"):
        shutil.copy2(f, ROLLBACK_DIR / "netplan" / f.name)
    shutil.copy2(NET_CONF, ROLLBACK_DIR / "network.conf")

def restore_configs() -> None:
    for f in NETPLAN_DIR.glob("*.yaml"):
        f.unlink()
    for f in (ROLLBACK_DIR / "netplan").glob("*.yaml"):
        dst = NETPLAN_DIR / f.name
        shutil.copy2(f, dst)
        dst.chmod(0o600)
    shutil.copy2(ROLLBACK_DIR / "network.conf", NET_CONF)

def main() -> int:
    if len(sys.argv) != 2:
        print("usage: switch_interface.py <new_iface>", file=sys.stderr)
        return 2
    new_if = sys.argv[1]

    conf = read_net_conf()
    old_if = conf.get("LAN_IF", "")
    router_ip = conf.get("ROUTER_IP", "192.168.50.1")
    _status.update({"old_iface": old_if, "new_iface": new_if, "started": time.time()})
    set_status("validate", ok=None, error=None)

    if not Path(f"/sys/class/net/{new_if}").exists():
        set_status("failed", ok=False, error=f"interface {new_if} not found"); return 1
    if new_if == old_if:
        set_status("failed", ok=False, error="interface is already active"); return 1
    ip_prefix = current_ip_prefix(old_if)
    if not ip_prefix:
        set_status("failed", ok=False, error=f"no IPv4 address on current interface {old_if}"); return 1
    ip_only = ip_prefix.split("/")[0]

    set_status("backup")
    backup_configs()

    try:
        set_status("apply")
        new_yaml = build_yaml(new_if, iface_mac(new_if), ip_prefix, router_ip, parse_nameservers())
        for f in NETPLAN_DIR.glob("*.yaml"):
            f.unlink()
        target = NETPLAN_DIR / "00-installer-config.yaml"
        target.write_text(new_yaml)
        target.chmod(0o600)
        apply_netplan()
        write_net_conf(new_if, router_ip)

        # Single-cable workflow: config is applied first, then the user moves
        # the cable. Wait for carrier on the new port before anything that
        # needs the interface up — networkd installs the static address only
        # once the link has carrier, and iptables.sh refuses to run without
        # an IP on LAN_IF.
        if not iface_carrier(new_if):
            set_status("wait_link")
            deadline = time.time() + WAIT_LINK_SEC
            while not iface_carrier(new_if):
                if time.time() > deadline:
                    raise RuntimeError(
                        f"кабель не появился на {new_if} за {WAIT_LINK_SEC} с")
                time.sleep(1)
            time.sleep(2)  # let the link settle / negotiate

        set_status("wait_ip")
        deadline = time.time() + 20
        while not current_ip_prefix(new_if):
            if time.time() > deadline:
                raise RuntimeError(f"networkd не назначил IP на {new_if} за 20 с")
            time.sleep(1)

        set_status("services")
        disable_usb_nic_offload(new_if)
        reapply_services()
        rebind_singbox(new_if)
        gratuitous_arp(new_if, ip_only)

        set_status("watchdog")
        wd_ok, wd_detail = watchdog(router_ip)
        if wd_ok:
            # final ARP refresh for clients that joined the party late
            gratuitous_arp(new_if, ip_only, repeats=3)
            set_status("done", ok=True, finished=time.time())
            shutil.rmtree(ROLLBACK_DIR, ignore_errors=True)
            return 0
        capture_debug(new_if, router_ip)
        raise RuntimeError(f"проверка связи не прошла за {WATCHDOG_SEC} с: {wd_detail}")
    except Exception as e:
        set_status("rollback", error=str(e))
        try:
            restore_configs()
            apply_netplan()
            # If the cable was already moved to the new port, give the user
            # time to put it back — the address and iptables need carrier.
            deadline = time.time() + WAIT_LINK_SEC
            while not iface_carrier(old_if) and time.time() < deadline:
                time.sleep(1)
            deadline = time.time() + 20
            while not current_ip_prefix(old_if) and time.time() < deadline:
                time.sleep(1)
            reapply_services()
            rebind_singbox(old_if)
            gratuitous_arp(old_if, ip_only)
            set_status("rolled_back", ok=False, error=str(e), finished=time.time())
        except Exception as e2:
            set_status("rollback_failed", ok=False,
                       error=f"{e}; rollback error: {e2}", finished=time.time())
        return 1

if __name__ == "__main__":
    sys.exit(main())
