"""
Letting something in, when the box is the edge of the network.

In inline topology the gateway is the edge router and the WAN is closed
unconditionally: replies and ping in, everything new dropped. That is the right
default and it stays the default. But it also meant there was no way to expose
a console, a home server or a WireGuard endpoint without editing a shipped
script, which the next upgrade overwrites.

So: a short list of what the household deliberately exposes, and nothing else.
Not a firewall rule editor. Routing on this box depends on the exact order of
fifteen rules in two mangle chains, and the last outage was one missing rule in
one of them; handing that ordering to a form multiplies the ways to produce a
gateway broken in a way nobody can see.

The first thing this has to do is harder than the forwarding, and it is the
reason the page is worth building at all: **say whether inbound can work here
before anyone spends an evening on a rule that cannot**. This gateway sits on
100.113.192.178/19 -- RFC 6598, the provider's own carrier-grade NAT. Nothing
from the internet reaches that address; the provider's NAT drops it long before
the cable. A form that accepts a port forward without saying so would be the
same lie as a check that cannot fail, just slower to discover.
"""
from __future__ import annotations

import ipaddress
import re

CGNAT = ipaddress.ip_network("100.64.0.0/10")

CONF_HEADER = ("# Generated by shunt from settings.json — do not edit.\n"
               "# proto  wan_port  to_ip  to_port\n")


def reachability(wan_cidr: str | None) -> dict:
    """
    Can a connection from the internet arrive at this gateway at all?

    Three answers, and two of them mean the forwarding list below is decoration.
    Said once, plainly, at the top of the page -- not discovered afterwards.
    """
    if not wan_cidr:
        return {"reachable": None, "class": "нет адреса",
                "why": "На WAN нет адреса — говорить о входящих соединениях рано."}
    try:
        ip = ipaddress.ip_interface(wan_cidr).ip
    except ValueError:
        return {"reachable": None, "class": "непонятный адрес",
                "why": "Адрес WAN не разобран."}
    if ip in CGNAT:
        return {
            "reachable": False,
            "class": "CGNAT провайдера",
            "why": ("Адрес %s принадлежит диапазону 100.64.0.0/10 — это NAT "
                    "провайдера, а не интернет. Входящие соединения до шлюза "
                    "не доходят: их отбрасывают на стороне провайдера. Проброс "
                    "портов здесь работать не будет, сколько бы правил ни "
                    "добавить. Нужен внешний («белый») адрес — обычно платная "
                    "услуга у того же провайдера." % ip),
        }
    if ip.is_private:
        return {
            "reachable": False,
            "class": "частный адрес",
            "why": ("Адрес %s частный (RFC1918) — значит, перед шлюзом стоит "
                    "ещё один маршрутизатор. Пока проброс не настроен и на нём, "
                    "входящие сюда не дойдут." % ip),
        }
    return {
        "reachable": True,
        "class": "публичный адрес",
        "why": ("Адрес %s публичный — входящие соединения доходят до шлюза, "
                "и всё, что открыто ниже, действительно открыто для интернета."
                % ip),
    }


def validate_rule(rule: dict, lan_cidr: str | None,
                  gateway_ips: set[str] | None = None,
                  existing: list[dict] | None = None) -> list[str]:
    """
    Refuse what should not be possible, and say why in a sentence.

    The one rule that is not a matter of taste: a forward may not point at the
    gateway itself. The administration interface and SSH live there, and a
    mistyped destination that exposed them would be the worst thing this
    feature could do. Pointing at a device on the LAN is the entire use case.
    """
    errors = []
    proto = str(rule.get("proto", "")).lower()
    if proto not in ("tcp", "udp"):
        errors.append("Протокол должен быть tcp или udp")

    for field, label in (("wan_port", "Внешний порт"), ("to_port", "Порт устройства")):
        try:
            v = int(rule.get(field))
        except (TypeError, ValueError):
            errors.append("%s: нужно число от 1 до 65535" % label)
            continue
        if not 1 <= v <= 65535:
            errors.append("%s: нужно число от 1 до 65535" % label)

    to_ip = str(rule.get("to_ip", "")).strip()
    try:
        dest = ipaddress.ip_address(to_ip)
    except ValueError:
        errors.append("Адрес устройства не разобран")
        dest = None

    if dest is not None:
        if gateway_ips and to_ip in gateway_ips:
            errors.append("Нельзя направить порт на сам шлюз: там живут "
                          "веб-интерфейс и SSH. Укажите устройство в локальной сети.")
        elif lan_cidr:
            try:
                net = ipaddress.ip_network(lan_cidr, strict=False)
                if dest not in net:
                    errors.append("Адрес %s вне локальной сети %s"
                                  % (to_ip, net))
            except ValueError:
                pass

    name = str(rule.get("name", "")).strip()
    if len(name) > 64:
        errors.append("Название длиннее 64 символов")
    if name and not re.match(r"^[\w \-.()/]+$", name, re.UNICODE):
        errors.append("В названии — только буквы, цифры и - . ( ) /")

    for other in (existing or []):
        if other.get("id") == rule.get("id"):
            continue
        if (str(other.get("proto", "")).lower() == proto
                and str(other.get("wan_port")) == str(rule.get("wan_port"))):
            errors.append("Внешний порт %s/%s уже занят правилом «%s»"
                          % (rule.get("wan_port"), proto,
                             other.get("name") or other.get("to_ip")))
    return errors


def cost_sentence(rule: dict, wan_cidr: str | None) -> str:
    """What this rule does, at the moment of adding it, in one sentence."""
    r = reachability(wan_cidr)
    who = "%s:%s" % (rule.get("to_ip"), rule.get("to_port"))
    if r["reachable"]:
        return ("Порт %s/%s станет доступен из интернета и попадёт на %s."
                % (rule.get("wan_port"), rule.get("proto"), who))
    return ("Правило направит порт %s/%s на %s — но снаружи он не откроется: %s"
            % (rule.get("wan_port"), rule.get("proto"), who, r["class"]))


def render_conf(rules: list[dict]) -> str:
    """
    The enabled rules, as a file the shell can read without a JSON parser.

    iptables.sh sources plain configuration and nothing else; giving it a second
    format to understand is how a datapath script grows a dependency it cannot
    fail safely without.
    """
    out = [CONF_HEADER]
    for r in rules:
        if not r.get("enabled", True):
            continue
        out.append("%s %s %s %s\n" % (str(r.get("proto", "")).lower(),
                                      r.get("wan_port"), r.get("to_ip"),
                                      r.get("to_port")))
    return "".join(out)


def parse_conf(text: str) -> list[dict]:
    """Read back what render_conf wrote -- the format is only real if it is."""
    rules = []
    for ln in text.splitlines():
        ln = ln.strip()
        if not ln or ln.startswith("#"):
            continue
        f = ln.split()
        if len(f) != 4:
            continue
        rules.append({"proto": f[0], "wan_port": int(f[1]),
                      "to_ip": f[2], "to_port": int(f[3])})
    return rules


# ── what is listening, and who could reach it ─────────────────────────────────

def ephemeral_range(path: str = "/proc/sys/net/ipv4/ip_local_port_range",
                    default: tuple[int, int] = (32768, 60999)) -> tuple[int, int]:
    """The ports the kernel hands out to clients. Read, not assumed."""
    try:
        lo, hi = open(path).read().split()[:2]
        return int(lo), int(hi)
    except (OSError, ValueError, IndexError):
        return default


def parse_listeners(ss_output: str, local_addrs: set[str] | None = None,
                    lan_ip: str | None = None, wan_ip: str | None = None,
                    ephemeral: tuple[int, int] | None = None) -> dict:
    """
    Everything accepting connections on this box, and who can actually get to it.

    The question anyone asks first when wondering whether a gateway is safe on a
    public address, and until now answerable only over SSH with `ss -tulnp`.

    Two things had to be learned from the real output before this was useful.
    Seventy sockets are open on this gateway and most are noise: fifty-odd are
    loopback-only, unreachable from anywhere but the box itself, and xray's
    per-flow UDP sockets appear with FOREIGN addresses in the local column --
    104.18.95.41:443 is not something listening here. So a listener is defined
    as a socket bound to a wildcard or to an address this machine actually
    holds; everything else is not a listener and is not shown. Loopback-only
    sockets are counted rather than listed, because "and fifty more you cannot
    reach" is the honest summary and a list of them is just frightening.

    A wildcard bind is also not the same as an exposed service -- the WAN chain
    drops new inbound -- and saying so is the difference between a list that
    informs and one that misleads.
    """
    local_addrs = local_addrs or set()
    eph_lo, eph_hi = ephemeral or ephemeral_range()
    listeners, loopback, transient = [], 0, 0
    for ln in ss_output.splitlines():
        f = ln.split()
        if len(f) < 5 or f[0] not in ("tcp", "udp"):
            continue
        local = f[4]
        addr, _, port = local.rpartition(":")
        addr = addr.strip("[]")
        if not port.isdigit():
            continue
        scope = addr.split("%")[0]
        iface = addr.split("%")[1] if "%" in addr else None

        if scope.startswith("127.") or scope == "::1":
            loopback += 1
            continue
        wildcard = scope in ("0.0.0.0", "*", "::")
        if not wildcard and scope not in local_addrs:
            transient += 1
            continue          # not a listener: a per-flow socket of some client
        # UDP has no LISTEN state, so a wildcard bind alone does not make a
        # service: xray keeps dozens of per-flow sockets on ephemeral ports and
        # they arrived here looking exactly like one. Nothing serves from the
        # range the kernel hands to clients, so that is the line -- read from
        # the kernel rather than guessed. TCP rows are all LISTEN already, and
        # a service may legitimately listen high (the SOCKS port is 1080).
        if f[0] == "udp" and eph_lo <= int(port) <= eph_hi:
            transient += 1
            continue

        proc = ""
        m = re.search(r'users:\(\("([^"]+)"', ln)
        if m:
            proc = m.group(1)

        if wildcard and iface:
            where = "на интерфейсе %s" % iface
            exposure = "доступен в этой сети"
        elif wildcard:
            where = "на всех интерфейсах"
            exposure = ("из интернета закрыт правилом WAN; "
                        "из локальной сети доступен")
        elif lan_ip and scope == lan_ip:
            where = "в локальной сети"
            exposure = "доступен устройствам в сети"
        elif wan_ip and scope == wan_ip:
            where = "на адресе провайдера"
            exposure = "закрыт правилом WAN, но слушает именно там"
        else:
            where = scope
            exposure = "доступен там, где этот адрес виден"

        listeners.append({"proto": f[0], "address": addr, "port": int(port),
                          "process": proc, "where": where, "exposure": exposure,
                          "wildcard": wildcard})
    # One row per service, not one per socket: sshd binds v4 and v6 separately
    # and listing it twice teaches nothing.
    seen, unique = set(), []
    for r in sorted(listeners, key=lambda r: (r["port"], r["proto"], r["address"])):
        key = (r["proto"], r["port"], r["process"], r["wildcard"])
        if key in seen:
            continue
        seen.add(key)
        unique.append(r)
    return {"listeners": unique, "loopback_only": loopback,
            "transient": transient}
